# Base image
FROM python:3.6.5-alpine

# Set working directory
WORKDIR /usr/src/app

# Add and install requirements
COPY ./requirements.txt/ /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Run the server
CMD python manage.py run -h 0.0.0.0